apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: arbor-build-pipeline-build-tt
spec:
  params:
  - name: git-app-repo-url
  - name: git-app-repo-name
  - name: git-app-repo-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: arbor-build-pipeline-build-deploy-pipeline-run-
      namespace: arbor-build-pipeline
      labels:
        pipeline: tekton
        deploy: argocd
    spec:
      serviceAccountName: pipeline-sa
      pipelineRef:
        name: arbor-build-pipeline-build-deploy-pipeline
      params:
      - name: git-app-repo
        value: $(tt.params.git-app-repo-name)
      - name: git-url
        value: $(tt.params.git-app-repo-url)

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: arbor-build-pipeline-build-git-tb
spec:
  params:
  - name: git-app-repo-url
    # Replace with path to the JSON resource you want, based on the Git provider that you're using (e.g. for AzureDevOps: resource.repository.remoteUrl)
    value: $(body.repository.url)
  - name: git-app-repo-revision
    value: main

---

apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: arbor-build-pipeline-build-el
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
  - bindings:
    - ref: arbor-build-pipeline-build-git-tb
    template:
      name: arbor-build-pipeline-build-tt