---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: arbor-build-pipeline-build-deploy-pipeline
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: git-app-repo
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: git-source
    - name: build-docker-image
      taskRef:
        name: build-docker-image
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/git-app-repo
      resources:
        inputs:
          - name: git-app-repo
            resource: git-app-repo
        outputs:
          - name: image-registry
            resource: image-registry
    - name: sync-application
      taskRef:
        name: argocd-task-sync-and-wait
      runAfter:
        - build-docker-image
      params:
        - name: flags
          value: --insecure # needed in this example only because the Argo CD server is locally hosted